services:
  - type: web
    name: virtualforge-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.simgen.main_clean:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: DEBUG
        value: false
      - key: CORS_ORIGINS
        value: "*"
      - key: HOST
        value: 0.0.0.0
    healthCheckPath: /health
